### ISSUE TITLE
Material-UI v1.0.0 support

### ISSUE THREAD

**Issue by alexbrazier** [TeamWertarbyte/material-ui-search-bar#10]
This module does not work with the new material ui.

It would be good to create a beta version of this that is compatible, ready for the official release of v.1.0.0, which should be soon.

- [x] Port the component (thanks @alexbrazier :tada:)
- [x] Fix styleguidist somehow
- [ ] Publish to npm with `@next` tag

**Comment by leMaik** [comment]
At the moment, none of our Material-UI components will work with Material-UI v1, as there are a lot of breaking changes. We'll port all of them, this component is a pretty simple one to start with. :+1:

**Comment by leMaik** [comment]
Thanks for the PR, I just edited this issue to track the progress. :wink:

**Comment by alexbrazier** [comment]
@leMaik Are you planning to do a release the the `next` tag as it is, or are you planning on making more changes first?

It would still be useful to have a release to use with the beta material-ui, as it currently works, it's just missing auto-complete (not sure if you want to add that back)

**Comment by leMaik** [comment]
Done :tada: It's v1.0.0-beta.1

**Comment by alexbrazier** [comment]
Awesome, thanks!

**Comment by leMaik** [comment]
One more thing, though. Why did you change `e.charCode === 13` to `e.key === 'Enter'`?
Using `charCode` [works on Android browsers](http://caniuse.com/#feat=keyboardevent-charcode) whereas key [does not](http://caniuse.com/#feat=keyboardevent-key), so I don't see a reason to change it?

**Comment by alexbrazier** [comment]
Yes, for some reason `e.charCode` always comes up as `0` for all keys. (Using chrome 59 mac)

**Comment by leMaik** [comment]
Virtually all except Android :wink: I changed that line so that it should work on _every_ browser, including Chrome 59 on mac. beta 2 is coming in a few minutes.

**Comment by alexbrazier** [comment]
👍 - As far as I can tell `e.keyCode` is meant to work in all browsers, including Android, it's `e.key` and `e.charCode` that only work in some, but your change looks good 😄

**Comment by leMaik** [comment]
Oh, yes... I misread that. :smile:
