### ISSUE TITLE
Ability to pass in style props to <IconButton />

### ISSUE THREAD

**Issue by tgoldenberg** [TeamWertarbyte/material-ui-search-bar#14]
I want to modify the styles of the `<IconButton />` that contains the search and close icons, but I don't believe this gives the ability to do so.

Could you expose `searchIconButtonStyles` and `closeIconButtonStyles`?

Or you could have the default `searchIcon` be an `<IconButton />` component, which can be overridden.

Thank you.

**Comment by leMaik** [comment]
I added a `iconButtonStyle` prop in v0.4.0.
