### ISSUE TITLE
How to install a module on react 17+?

### ISSUE THREAD

**Issue by Vitosiy** [TeamWertarbyte/material-ui-search-bar#141]
Greetings
How to install a module on react 17+?
The commit indicates that version support has been added, but npm does not install the module, since there is no such support in the releases known to it

**Comment by leMaik** [comment]
See #112 for a fork that seems to support React 17.

**Comment by Vitosiy** [comment]
You will do it?)

**Comment by leMaik** [comment]
Fixed in v1.0.1

**Comment by Vitosiy** [comment]
Thank you)
