### ISSUE TITLE
onRequestSearch, value property usage

### ISSUE THREAD

**Issue by BearandYoon** [TeamWertarbyte/material-ui-search-bar#16]
I am trying to use material-ui-search-bar component but I can't get value inputed from onRequestSearch and value property.
                                <SearchBar
                                    onChange={this.onChangeSearch}
                                    onRequestSearch={this.onSearchRequest}
                                    value={this.state.searchValue}
                                    style={{
                                        margin: '20px auto 0',
                                        maxWidth: 800
                                    }}
                                />

    onSearchRequest = () => {
        console.log('searchInstances = ', this.state.searchValue);
    };

**Comment by leMaik** [comment]
This is a _controlled_ component, you need to save the input value in the state: `onChange={(value) => this.setState({ searchValue: value })`

**Comment by ReneCode** [comment]
I aggree to Bearand.  
the ``onChange```callback gets the new value - that is fine.
but the ```onRequestSearch```does not.

or please explain me what a _controlled_ component is

**Comment by leMaik** [comment]
@ReneCode You need to store the value in your state in `onChange` and then use that value in your `onRequestSearch` handler.

```
<SearchBar
  value={this.state.value}
  onChange={(newValue) => this.setState({ value: newValue })}
  onRequestSearch={() => doSomethingWith(this.state.value)}
/>
```

**Comment by adam-nielsen** [comment]
Definitely would be helpful to have this snippet in the example given in the `README`!

**Comment by leMaik** [comment]
@adam-nielsen It's a very basic thing to do in React, but feel free to add some usage examples to the readme via a PR. :wink:

**Comment by leMaik** [comment]
@adam-nielsen It's a bit late, but I just added the example to the readme. :sweat_smile:

**Comment by adam-nielsen** [comment]
@leMaik Many thanks!  Sorry I didn't get time to do a PR for it!
