### ISSUE TITLE
no placeholder ?

### ISSUE THREAD

**Issue by zhangwei900808** [TeamWertarbyte/material-ui-search-bar#18]
I want to use Chinese in my component but I cant find it ,no placeholder?

**Comment by leMaik** [comment]
I'm afraid I don't understand what you mean with "no placeholder"?

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/30002070-d7480836-90d2-11e7-8996-9df1d5fca7da.png)
I mean is this name I want to change

**Comment by leMaik** [comment]
Allright, it's `hintText`.

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/30008242-f7812c68-914f-11e7-8620-668dc7ac8d62.png)
<SearchBar
                                hintText="搜索"
                                onChange={() => console.log('onChange')}
                                onRequestSearch={() => console.log('onRequestSearch')}
                                className={classes.searchBar}
                            />

I set hitTest in my SearchBar but is error

**Comment by leMaik** [comment]
This is just a warning. We'll fix that, but it should still work and set the placeholder text.

**Comment by zhangwei900808** [comment]
"material-ui-search-bar": "^1.0.0-beta.3",

**Comment by leMaik** [comment]
@zhangwei900808 Sorry for the late response. :cry: It's `placeholder` in the 1.0.0-beta version.
