### ISSUE TITLE
working with material-ui v1

### ISSUE THREAD

**Issue by treavies** [TeamWertarbyte/material-ui-search-bar#19]
hi i`m working with material-ui v1 i see u have fixed this bug for material-ui v1. but i`m still newbie so i don`t know how to update this npm plugin with the latest version of your work. 

please help me. thankyou

**Comment by leMaik** [comment]
You need to install the latest beta version using `npm install --save material-ui-search-bar@beta`.

**Comment by toolaugh** [comment]
I have the same questions. Recently, I have change version to v1. There are some changes in components with new version. It does not run  ....

**Comment by leMaik** [comment]
@toolaugh Please read the comment above. You need the latest beta version of this plugin in order to use material-ui v1.

**Comment by toolaugh** [comment]
@leMaik thanks.
