### ISSUE TITLE
Entry file not found

### ISSUE THREAD

**Issue by kMeillet** [TeamWertarbyte/material-ui-search-bar#2]
I've some trouble when i import the SearchBar component.

```js
import SearchBar from 'material-ui-search-bar'
```

**Got :** Module not found.

The main entrypoint in "package.json" is incorrect  : 

```json
  "main": "lib/index.js",
```

Only a small fix will allow us to use it :) .

**Comment by leMaik** [comment]
I just checked this and the main entrypoint is correct and the file is there. The problem is that we don't export the search bar as default export, so you need to use it like this (for now):

```
import { SearchBar } from 'material-ui-search-bar'
```
