### ISSUE TITLE
Autocomplete not working with material-ui v1

### ISSUE THREAD

**Issue by harsha31** [TeamWertarbyte/material-ui-search-bar#21]
Installed  search bar npm install --save material-ui-search-bar@beta. auto-populating is not working. 

```
<SearchBar value = {this.state.searchKey}
				onChange={(value) => {this.setState({searchKey:value})}}
              	                 onRequestSearch={this.onSearchRequest.bind(this)}
				dataSource = {this.state.source}
				
            />

**Comment by leMaik** [comment]
Unfortunately, `AutoComplete` was removed in material-ui v1 and thus isn't available anymore in this search bar. :confused:

**Comment by saschb2b** [comment]
We need to refactore it with something like https://github.com/moroshko/react-autosuggest

**Comment by leMaik** [comment]
@saschb2b We might use react-autosuggest to create a new _material-ui-legacy-autocomplete_ component that just behaves like the old `AutoComplete`.

**Comment by harsha31** [comment]
@leMaik Autosuggest is added in material-ui v1. When can we expect autocomplete in searchbar??

**Comment by leMaik** [comment]
@harsha31 Where? I don't see an `AutoComplete` component in the v1 branch. There is only a demo on how to implement it using react-autosuggest.

There is no ETA for updating this component. It will be updated when we have time and want to do it, or someone submits a PR. :wink:

**Comment by tifa2UP** [comment]
+1.

Had to downgrade to Material-UI v0.18 for this.

**Comment by afparsons** [comment]
Am I to understand that this package in its current state (even `material-ui-search-bar@beta`), will absolutely **not** function with any v1 of `material-ui` (ex: `material-ui 1.0.0-beta.21`) ?

**Comment by leMaik** [comment]
@afparsons It will work, but auto-complete won't work at the moment. We are really looking forward to anyone who wants to implement this. I mean, you obviously need it, so why not take some time and submit a PR? :smiley:

**Comment by afparsons** [comment]
@leMaik  Alright, time to show my cards. I'm a total noob here. I'd love to submit a PR, but 1) timeliness and 2) quality would both be of concern :laughing: . Perhaps in the next two weeks I could take a look, as it seems to not be a priority for you all.

Could I have a 30 second explanation of what `auto-complete` is and for what it is needed? Or point me to the correct doc... ?

**Comment by leMaik** [comment]
@afparsons It's a popup that will open below the search bar and show results/suggestions as you type (like your favorite search engine does). Material-UI 0.x had this, [here is a demo](http://www.material-ui.com/#/components/auto-complete).

**Comment by gauravdhiman** [comment]
I see there is a v1.x.x beta tag on repo: https://github.com/TeamWertarbyte/material-ui-search-bar/tree/v1.0.0-beta.4. It should work with material-ui 1.x.x, but could not find that package on NPM. Do you have that release or not yet ?

Please let me know how to install v1.x.x of this repo using NPM or GIT.

**Comment by saschb2b** [comment]
@gauravdhiman just use the pre-release channel with the @beta tag
`npm install material-ui-search-bar@beta`

**Comment by KaushalyaPradeep** [comment]
Autocomplete not working even with `"material-ui-search-bar": "^1.0.0-beta.4",`

**Comment by lexprom** [comment]
These commands help me:
`yarn add @material-ui/core`
`yarn add @material-ui/icons`
Idk my answer is relevant or not. But I hope I helped someone :smile:

**Comment by clymbe** [comment]
@leMaik Any suggestions on a possible implementation for the autocomplete feature? One idea is to use the Autocomplete component from @material-ui/lab/Autocomplete. However, its not part of @material-ui/core/. Would that be ok?

**Comment by nithins** [comment]
@leMaik Any suggestions for an autocomplete implementation? I thought the Autocomplete component from @material-ui/lab/ could work. But my concern is that it was not part of @material-ui/core/.
