### ISSUE TITLE
Allow passing in handleCancel prop

### ISSUE THREAD

**Issue by nwshane** [TeamWertarbyte/material-ui-search-bar#22]
The current version creates a `handleCancel` callback that is hardcoded. I'm using redux in my application, so I'd like to pass a `handleCancel` callback in as a property which will set the value of `state.search` to an empty string.

**Comment by leMaik** [comment]
We already call the `onChange` handler with an empty string in the `handleCancel` method, so you just need to handle that.

**Comment by nwshane** [comment]
@leMaik Ah, I think I see the problem.`onChange` is called directly on the event object in the `handleInput` method, but `onChange` is called with an empty string in the `handleCancel` method. When I click the cancel button, my `onChange` handler is expecting an `event` object with `event.target.value`, and so I get the error `Cannot read property 'value' of undefined`.

**Comment by nwshane** [comment]
@leMaik How about this for a fix? Instead of...

```
handleCancel () {
  this.setState({active: false, value: ''})
  this.props.onChange('')
}
```

Do this:

```
handleCancel () {
  this.setState({active: false, value: ''})
  this.props.onChange({target: {value: ''}})
}
```

**Comment by nwshane** [comment]
@leMaik I've been trying to link a local, forked version of this repository in order to test this change (and to potentially make a PR), but I'm having trouble doing so. I'm getting this error:

```
removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

It doesn't look like multiple copies of React are loading (output from `yarn list react` is just one copy). Could this have something to do with the AutoComplete ref? Sorry, I'm a little out of my league here - haven't used refs before.

**Comment by leMaik** [comment]
@nwshane I'd prefer to always call `onChange` with the new value instead. That would be a breaking change, but a PR would be highly appreciated! :+1:
