### ISSUE TITLE
Allow for IconButton style overrides in the material v1 build

### ISSUE THREAD

**Issue by bklever** [TeamWertarbyte/material-ui-search-bar#23]
Current master allows for overriding iconButtonStyle with a prop. Any chance of adding the same prop to the beta build, or just allow for the current styles prop to override them?

**Comment by leMaik** [comment]
We'll do this by allowing to override the internal styles using the `classes` prop, the same way as material-ui@1.0.0-beta does it. :+1:

**Comment by d0bz** [comment]
If I use iconButtonStyle as prop then same prop is added to autocomplete input which creates error into console as unknown prop.
SearchBar.js inputProps = _objectWithoutProperties array to exclude should have iconButtonStyle key. 

Or am i using this wrong?

**Comment by leMaik** [comment]
@d0bz It's not yet possible to use that prop in the material-ui v1.0.0 build. That's why this issue is not closed yet.

**Comment by leMaik** [comment]
This is possible in the next release by using `withStyles` in your component and supplying a classname with `classes={{ iconButton: classes.yourIconButtonStyle }}`
