### ISSUE TITLE
Turn off spellcheck

### ISSUE THREAD

**Issue by strin** [TeamWertarbyte/material-ui-search-bar#24]
![image](https://user-images.githubusercontent.com/2183232/31924348-503f76be-b835-11e7-9d81-be19da4a73e5.png)

Currently, there is no way to turn off spellcheck. The HTML5 standard requires specify "spellcheck=false" in <input/> 

See

https://stackoverflow.com/questions/4524000/turn-off-chrome-safari-spell-checking-by-html-css

**Comment by saschb2b** [comment]
@strin Good point, google does that, too! Will add that in the coming days.

**Comment by saschb2b** [comment]
Version 0.4.1 does have grammar and spelling check disabled by default.
