### ISSUE TITLE
Copy&Paste error

### ISSUE THREAD

**Issue by FlorianKoerner** [TeamWertarbyte/material-ui-search-bar#3]
See here: https://github.com/TeamWertarbyte/material-ui-search-bar/blob/master/src/index.js#L1

Rating instead of SearchBar

**Comment by leMaik** [comment]
Good catch, thank you! :see_no_evil:

**Comment by FlorianKoerner** [comment]
Thanks for the quick fix. Could you publish a new release, please? 😃

**Comment by leMaik** [comment]
Yeah, I just tried but I can't. :sweat_smile: @saschb2b to the rescue! :rotating_light:

**Comment by saschb2b** [comment]
Oh god. Such shame. Just published 0.1.1. Thanks for the report.
