### ISSUE TITLE
Failed to compile. search bar 

### ISSUE THREAD

**Issue by sareh88** [TeamWertarbyte/material-ui-search-bar#30]
<SearchBar
            onChange={() => console.log('onChange')}
            onRequestSearch={() => console.log('onRequestSearch')}
            style={{
              margin: '0 auto',
              maxWidth: 800
            }}
          />

i got this error messege when i run my app,,, i am using material ui 1
Failed to compile.

./node_modules/material-ui-search-bar/lib/components/SearchBar/SearchBar.js
Module not found: Can't resolve 'material-ui/AutoComplete' in '/home/sareh/Desktop/skypeClone/SkypeClone/client/node_modules/material-ui-search-bar/lib/components/SearchBar'

**Comment by saschb2b** [comment]
The stable version of this component is not yet mui 1.0 compatible.
AutoComplete is not present in mui 1.0 only in a separat package.
Try our next branch via `npm i --save 1.0.0-beta.3`
It doesn't have auto complete.

You're welcome to submit a PR for this port :)

**Comment by sareh88** [comment]
thanks for fast replay :+1:
