### ISSUE TITLE
Is there a simple way to implement this into a Rails app?

### ISSUE THREAD

**Issue by jackmoody11** [TeamWertarbyte/material-ui-search-bar#31]
I was wondering what needs to be done to use this in a Rails app? Mostly just need to know which files to include in my javascript folder and what HTML I should write to render the SearchBar.

**Comment by leMaik** [comment]
This is a [React](https://reactjs.org/) component that uses [Material-UI](https://material-ui-next.com/). If you're using both in your front-end stack, you can use this. There are plenty good React tutorials out there. Try it, it's fun! :+1: 

Here's a tutorial on how to use React with Ruby on Rails: https://medium.com/react-on-rails/free-tutorial-how-to-use-react-with-webpacker-and-rails-5-1-92af8e8d9d63 (I don't use Rails, so I can't tell if it is good, just wanted to point you in the right direction)
