### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by redouane59** [TeamWertarbyte/material-ui-search-bar#34]
Hello, I have this error message : 

> Failed to compile
> ./node_modules/material-ui-search-bar/lib/components/SearchBar/SearchBar.js
> Module not found: Can't resolve 'material-ui/IconButton' in 'D:\Redouane\WebstormProjects\soccer-factory\node_modules\material-ui-search-bar\lib\components\SearchBar'

I tried everything 
npm i --save material-ui-search-bar
npm i --save material-ui-search-bar@beta
npm i --save material-ui-search-bar@1.0.0-beta.3

What did I do wrong ?

**Comment by leMaik** [comment]
Which version of material-ui are you using?

**Comment by redouane59** [comment]
I just did a npm install material-ui and I think i get the version 0.20

**Comment by leMaik** [comment]
Which version of material-ui do you want to use? If you want to use material-ui 0.x, you need material-ui-search-bar@latest. If you want to use material-ui 1.0.0 (preferred :wink:), you need to use material-ui-search-bar@beta.

**Comment by redouane59** [comment]
It works ! Thank you very much :)

**Comment by redouane59** [comment]
In fact i don't have

**Comment by leMaik** [comment]
This is not an issue about this component. Please follow [this getting started guide](http://www.material-ui.com/#/get-started/usage) for Material-UI. They also have a Gitter chat room and a stackoverflow tag to help you. :+1:
