### ISSUE TITLE
SearchBar for material-ui 1.0.0-beta.33

### ISSUE THREAD

**Issue by somarjun** [TeamWertarbyte/material-ui-search-bar#35]
I'm trying to use this search bar and the latest materialUI doesn't actually have an AutoComplete component
Compilation error: Module not found: Can't resolve 'material-ui/AutoComplete' in '/Users/../node_modules/material-ui-search-bar/lib/components/SearchBar'

**Comment by roshtov6** [comment]
@somarjun I ran into the same issue, and this solved the case for me https://github.com/TeamWertarbyte/material-ui-search-bar/issues/33 :

> You need to use npm i --save material-ui-search-bar@beta to install the beta version that is compatible with material-ui 1.0
