### ISSUE TITLE
Need an option for a case insensitive search

### ISSUE THREAD

**Issue by kehoej** [TeamWertarbyte/material-ui-search-bar#36]
We need an option for case insensitive searches.

**Comment by hrdymchl** [comment]
+1 for this

**Comment by leMaik** [comment]
You can use `inputProps` to pass additional props to the underlying `AutoComplete` component. You can use this to pass custom filters, as shown [here](http://www.material-ui.com/#/components/auto-complete). `<SearchBar inputProps={{ filter: yourFilterFunction }} />`
