### ISSUE TITLE
debounce time

### ISSUE THREAD

**Issue by sergiolpf** [TeamWertarbyte/material-ui-search-bar#39]
Hi all,

I would like to suggest that you add a debounce functionality, I am using the search and calling the api on every onChange and had to use lodash debounce method in order to make it work as I wanted.

Cheers

**Comment by leMaik** [comment]
Good idea, but this can (and should!) be done on the user's (e.g. your) side. Here is some code to show how it could be done.

```
import { debounce } from 'lodash';

class YourComponent extends React.Component {
  handleSearch = debounce((value) => {
    // TODO do things
  }, 1000);

  render () {

    return (<SearchBar… onChange={this.handleSearch} />)
  }
}

**Comment by chitgoks** [comment]
has this been added? or in progress? i do not see the option in the readme

**Comment by leMaik** [comment]
@chitgoks as I said:

> Good idea, but this can (and should!) be done on the user's (e.g. your) side.
