### ISSUE TITLE
Component should have a disabled prop.

### ISSUE THREAD

**Issue by bernalrs** [TeamWertarbyte/material-ui-search-bar#4]
The material-ui-search-bar component should have a disabled prop that is fed into the underlying autocomplete.

Name	Type	Default	Description
disabled   bool	False	disables the underlying autocomplete component.

**Comment by saschb2b** [comment]
@bernalrs good idea. will implement this. Any ideas on how to style this?
Just using the default disabled style from autocomplete? Or any further visualisation via custom icons

**Comment by leMaik** [comment]
@saschb2b The icon should become a little transparent (like [here](https://github.com/TeamWertarbyte/material-ui-password-field/blob/master/src/PasswordField.js#L36) to keep it consistent across our components.

**Comment by bernalrs** [comment]
Hi, 

FYI I have implemented the changes and I will submit a pull request soon.

Regards

**Comment by saschb2b** [comment]
Thanks for the prop.
