### ISSUE TITLE
Plain <SearchBar/> component is so slow it almost crashes the tab

### ISSUE THREAD

**Issue by phdowling** [TeamWertarbyte/material-ui-search-bar#40]
I have a very simple component like this:

```
import React from 'react';
import SearchBar from 'material-ui-search-bar'


class SearchView extends React.Component{
	render() {
		return(
			<div class="search-component">
				<SearchBar/>
			</div>
		);
	}
}


export default SearchView;
```

When I start this and type anything, the letters appear literally seconds after I type and the whole thing is incredibly unresponsive. What's going on?

The app is created using `create-react-app`. I installed via `npm i --save material-ui-search-bar`.

**Comment by leMaik** [comment]
Uhm… Is your component really "like this" or more complex? :wink: It works pretty decent for us.

What you describe sounds like everything re-renders whenever you type in a new letter.
Are you using Redux and connected the search field to it? Are you setting some state and re-rendering a very large part every time the content changes?

**Comment by phdowling** [comment]
The code is copy-pasted, no redux in the whole app. The SearchView Component was rendered inside a simple component as well (react-router with two routes, material-ui, bootstrap imported..)

With an open developer console, I actually see a bit more than I originally reported: exceptions are being thrown for every letter typed:
``` 
TypeError: this.props.onChange is not a function (SearchBar.js:164)
```

Seems like that could be the cause. I'm quite new to React (just learning, building a very simple frontend), so I can't contribute too much on seeing what exactly is happening right now.

**Comment by leMaik** [comment]
Looks like you're not passing in a `onChange` handler; it should be _a function_ that is called whenever the input changes.

**Comment by leMaik** [comment]
I'm closing this due to inacticity. @phdowling Feel free to open a new issue if you have any further questions. :+1:
