### ISSUE TITLE
beta does not receive props like dataSource when using material-ui@next

### ISSUE THREAD

**Issue by haemse** [TeamWertarbyte/material-ui-search-bar#42]
```
        <SearchBar
          onChange={(value) => {console.log("onChangeEv")}}
          dataSource={["array"]}
          hintText = {"this is a hint text"}
          onRequestSearch={() => console.log('onRequestSearch')}
          style={{
            margin: '0 auto',
            maxWidth: 800
          }}
        />
```

In Browser:
index.js:2178 Warning: React does not recognize the `**dataSource**` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datasource` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Input)
    in Input (created by WithStyles(Input))
    in WithStyles(Input) (created by SearchBar)
    in div (created by SearchBar)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by SearchBar)
    in SearchBar (at App.js:23)
    in App (at index.js:7)
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 Warning: React does not recognize the `**hintText**` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hinttext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Input)
    in Input (created by WithStyles(Input))
    in WithStyles(Input) (created by SearchBar)
    in div (created by SearchBar)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by SearchBar)
    in SearchBar (at App.js:23)
    in App (at index.js:7)
__stack_frame_overlay_proxy_console__ @ index.js:2178

**Comment by leMaik** [comment]
Please remove swear words in your example the next time you create an issue.

**Comment by haemse** [comment]
oh, sorry, I forgot I had those example strings in there, sorry ;-)

just figured out it has been removed. thanks though
