### ISSUE TITLE
How do i change the icon height and width?

### ISSUE THREAD

**Issue by sschiang** [TeamWertarbyte/material-ui-search-bar#43]
I'm able to change the height and width of the bar with:

        <SearchBar
          onChange={() => console.log('onChange')}
          onRequestSearch={() => console.log('onRequestSearch')}
          style={{ height: 30, width: 600 }}
        />

but the height of the search and close icon is too large. Is there anyway to change just the style for them without passing in new icons in closeIcon and searchIcon?

**Comment by leMaik** [comment]
Are you using Material-UI 1.0.0? We could add a `classes` property to change the styles. Otherwise, you'll have to specify the entire icon (it's a more powerful way, though).

**Comment by leMaik** [comment]
You can now add a custom icon classname using the `classes` property, i.e. `classes={{ icon: classes.searchBarIcon }}`. You need to use `withStyles` to get a `classes` property injected, similar to all other Material-UI components in v1.0.0

**Comment by caroe233** [comment]
Hi,
it seems that this is not possible for Typescript. Any chance to extend the description of SearchBar to something like React.ComponentType<SearchBarProps & WithStyles>'icon'>> ? Or am I missing out the right way of doing this here?

Thanks
Caroline
