### ISSUE TITLE
 onRequestSearch should not be required 

### ISSUE THREAD

**Issue by maibono** [TeamWertarbyte/material-ui-search-bar#48]
Currently I am getting error that onRequestSearch is required, but I don't have any functionality for that feature in my app
> Warning: Failed prop type: The prop `onRequestSearch` is marked as required in `SearchBar`, but its value is `undefined`.`

**Comment by benamatare** [comment]
onRequestSearch is submit, you're using a search bar that doesn't submit anything? You could just plug a do-nothing function to alleviate that.

**Comment by leMaik** [comment]
@benamatare is right. We made this prop required so that people know when they are not using this component as intended (helps finding errors). If you really don't want to handle submitting the search form, use a no-op function.

**Comment by leMaik** [comment]
Just realized that if you're using the `onChange` prop to search while typing, `onSubmit` actually _is_ not required.

**Comment by leMaik** [comment]
@maibono It's not required in beta 8: https://github.com/TeamWertarbyte/material-ui-search-bar/blob/v1.0.0-beta.8/src/components/SearchBar/SearchBar.js#L201

That said, releasing beta 9 was on my todo-list anyway, so I'll do that.
