### ISSUE TITLE
hintText not working (but placeholder works)

### ISSUE THREAD

**Issue by felipeaugustox** [TeamWertarbyte/material-ui-search-bar#49]
When I add hintText value, it's not working, I tried placeholder, and it seems to be the correct field name ...

**Comment by benamatare** [comment]
Component source code is not updated, or was redacted.. placeholder is working.

**Comment by felipeaugustox** [comment]
@benamatare yep, placeholder works, but there isn't placeholder field at the docs, but I don't know if the incorrect is at the docs (and we should use placeholder instead) or at the code.

**Comment by leMaik** [comment]
It's incorrect in the docs (they weren't updated for the v1 port). I'll fix that.
