### ISSUE TITLE
The context `muiTheme` is marked as required in `Paper`, but its value is `undefined`.

### ISSUE THREAD

**Issue by mwinner313** [TeamWertarbyte/material-ui-search-bar#50]
The context `muiTheme` is marked as required in `Paper`, but its value is `undefined`.
    in Paper (created by SearchBar)

what cause this error ? i allready wrapped my components with muiThemeProvider everything is fine .

**Comment by saschb2b** [comment]
@mwinner313 can you post a sample code?
I assume you are using the mui 1.0 searchbar component and your app still uses mui beta.

**Comment by mwinner313** [comment]
yes and sorry , i did fix it
