### ISSUE TITLE
"TypeError: Cannot read property 'prepareStyles' of undefined" on inclusion of SearchBar component

### ISSUE THREAD

**Issue by wfehrnstrom** [TeamWertarbyte/material-ui-search-bar#55]
I've using material-ui-search-bar v0.4.2.  As part of my project, for my root node I include a MuiThemeProvider from material-ui like so:
`const theme = createMuiTheme(
{
  overrides: {
    /* No Fillets on buttons */
    MuiButton: {
      root: {
        borderRadius: 0,
        fontWeight: 400,
      }
    }
  },
  palette: {
    primary: {
      main: '#FF5959',
    },
  },
  typography: {
    fontFamily: [
      'Aileron',
    ].join(","),
  }
})
ReactDOM.render(
  <MuiThemeProvider theme = {theme}>
    <Provider store={store}>
      <App />
    </Provider>
  </MuiThemeProvider>
  , document.getElementById('root'));`

This is in order to correctly style some of my other components.  Now however,  I include SearchBar in my product like so:
`<SearchBar
            onChange={
              () => {
              console.log('change!')
              }}
            onRequestSearch={
              () => {
                console.log('Request Search')
              }
            }
            style={{
              margin: '25px 0'
            }}
          />`

and a TypeError is thrown that 'Cannot read property 'prepareStyles' of undefined' inside of Paper.render, Paper.js line 101.  How should I resolve this issue.  I have tried wrapping SearchBar in a separate MuiThemeProvider component however according to the material-ui docs this is not recommended and it does not work for me anyway.  Thanks!

**Comment by leMaik** [comment]
Which version of material-ui are you using?

**Comment by wfehrnstrom** [comment]
@material-ui/core v1.4.3

**Comment by leMaik** [comment]
@wfehrnstrom The 0.x versions of material-ui-search-bar are incompatible with material-ui 1.0.0 and later, and npm should have told you so. :wink: 

Please use material-ui-search-bar 1.0.0-beta (`npm i --save material-ui-search-bar@beta`) instead. Feel free to open new issues if you encounter any issues with that version.
