### ISSUE TITLE
console warning

### ISSUE THREAD

**Issue by frodestorhaug** [TeamWertarbyte/material-ui-search-bar#56]
warning.js:33 Warning: React does not recognize the `cancelOnEscape` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `cancelonescape` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Unknown event handler property `onCancelSearch`. It will be ignored.

**Comment by leMaik** [comment]
Thanks for reporting this. The good thing is that these are only warnings. :grimacing:
