### ISSUE TITLE
Clearing search field

### ISSUE THREAD

**Issue by abedmurrar** [TeamWertarbyte/material-ui-search-bar#57]
Can you bring back the onClear Props ?
because when i click the close button that clears the search field, it doesn't change the state nor when using onChange props it doesn't fire. so the state remains the same

**Comment by leMaik** [comment]
I don't know why it doesn't clear the search field, seems to be an issue on your side? :thinking: 

The code is pretty clear: https://github.com/TeamWertarbyte/material-ui-search-bar/blob/master/src/components/SearchBar/SearchBar.js#L93

**Comment by abedmurrar** [comment]
it does clear the string but let me explain
i have a big container and the search bar is a child component in it (seperate component), so the state is saved in the container, to change the state i use handleChangeQuery function and i pass it as props to the search component then i make onChange=props.handleChangeQuery .. all good.now when i type a string of characters then press close button,my state in the container doesn't change, what i mean is when all string is cleared i need to make another API call

**Comment by abedmurrar** [comment]
i was using older version, didn't know about onCancelSearch
