### ISSUE TITLE
Warning  Unknown event handler property `onCancelSearch`. 

### ISSUE THREAD

**Issue by nishant-ibono** [TeamWertarbyte/material-ui-search-bar#58]
i have assigned a function to onCancelSearch prop which resets the results when cancelled. Its working fine but I am getting this  warning: 

> Warning: Unknown event handler property `onCancelSearch`. It will be ignored.
    in div (created by Input)
    in Input (created by WithStyles(Input))
    in WithStyles(Input) (created by SearchBar)
    in div (created by SearchBar)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by SearchBar)
    in SearchBar (created by WithStyles(SearchBar))
    in WithStyles(SearchBar) (at Stores.js:558)
    in div (at Stores.js:532)
    in Stores (created by Route)
    in Route (at Main.js:38)
    in Switch (at Main.js:32)
    in main (at Main.js:31)
    in Main (created by Route)
    in Route (created by withRouter(Main))
    in withRouter(Main) (at App.js:83)
    in div (at App.js:81)
    in MuiThemeProvider (at App.js:90)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp
    in Router (created by HashRouter)
    in HashRouter (at index.js:37)
    in ErrorBoundary (at index.js:36)

**Comment by maibono** [comment]
Fixed in the latest release, you can close this.

**Comment by leMaik** [comment]
Allright, glad you could solve this. :+1:
