### ISSUE TITLE
Small width containers: icons overflow paper

### ISSUE THREAD

**Issue by Apollinaire** [TeamWertarbyte/material-ui-search-bar#62]
When the Searchbar is within a container with width under 280px the icons overflow the paper : 
![sans titre](https://user-images.githubusercontent.com/5938985/45894661-58c53800-bdcf-11e8-95e1-3539f1f021e2.png)
To reproduce this, go to https://mui.wertarbyte.com/#material-ui-search-bar and resize the window until you see the search icon exit the paper container (this is where the screencap was taken).
Could it be possible to have  a more mobile friendly searchBar? or maybe make a dense version? 
I tried playing with the component's source but was not able to find a fix. I don't know where this is coming from. Maybe using the [input adornments](https://material-ui.com/demos/text-fields/#input-adornments) to display the icons could help ?

**Comment by leMaik** [comment]
@Apollinaire Thanks for reporting this, it's fixed in v1.0.0-beta.12
