### ISSUE TITLE
Is there a way to lose focus (blur) after onRequestSearch?

### ISSUE THREAD

**Issue by czelusniakdawid** [TeamWertarbyte/material-ui-search-bar#66]
Hi @leMaik,

I've noticed that search input does NOT lose focus after submitting data (when `onRequestSearch` occurs). Is there a way to programmatically lose focus from search input immediately after `onRequestSearch`? Because of that keyboards on mobile devices don't hide when data are submitted and focus is still present on search input.

Thank you!

**Comment by leMaik** [comment]
Hi @czelusniakdawid, there is no way to do that at the moment. Feel free to start a PR that adds `blur` and `focus` methods to the component, so that you can blur/focus it by getting a ref and calling `searchRef.blur()`. :+1: 

Otherwise, I'll look into this soon™

**Comment by czelusniakdawid** [comment]
Thanks for your answer! Temporary workaround without using `ref` is just calling:
```
document.activeElement.blur();
```
inside `onRequestSearch`, but it would be nice to have `focus` and `blur` methods on the component.

**Comment by leMaik** [comment]
That's an incredibly ugly, non-React-y work-around :sweat_smile: I'll leave this open until it is implemented.

**Comment by leMaik** [comment]
It's been a while, but this is finally implemented. There's an example here: https://github.com/TeamWertarbyte/material-ui-search-bar/blob/master/src/components/SearchBar/SearchBar.md
