### ISSUE TITLE
Close Icon onClick function

### ISSUE THREAD

**Issue by devans-k4** [TeamWertarbyte/material-ui-search-bar#67]
Is there a way to have an onClick function triggered when the close icon is selected. My use case is that when the clear text icon is selected, my data is still filtered because there isn't a trigger to bring all the data back.

**Comment by leMaik** [comment]
@devans-k4 Did you close this by accident or did you solve the issue?

**Comment by devans-k4** [comment]
I solved the issue thanks. I did not see the prop "onCancelSearch" in your npm docs but as soon as I left this issue, I saw the exact prop I was looking for in your GitHub docs. Thanks for the quick response!

**Comment by leMaik** [comment]
Yeah, it's the `beta` tag on npm. We should finally bump the package version.
https://www.npmjs.com/package/material-ui-search-bar/v/1.0.0-beta.13
