### ISSUE TITLE
Issue : Module not found: Can't resolve 'material-ui/AutoComplete' 

### ISSUE THREAD

**Issue by nags-git** [TeamWertarbyte/material-ui-search-bar#73]
When trying to use the component it is throwing error Issue : Module not found: Can't resolve 'material-ui/AutoComplete' n 'C:\..\..\node_modules\material-ui-search-bar\lib\components\SearchBar', after installing the all modules as required. this is happening in both enchaned and previous version of control also @searchbar.js

**Comment by jpacora** [comment]
The same here.

**Comment by yohanliyanage** [comment]
I came across the same issue as well. I switched to the pre-release channel (@beta) and that version works fine. Looks like this happens because Material UI v1 removed AutoComplete and the stable channel of this component depends on it. So it is not compatible with MUI V1.

**Comment by leMaik** [comment]
Indeed, the beta is for Material-UI v1 and later. It's been around for over a year, so even if it is tagged as "beta", it's just as stable and maintained as the "latest" version.

One day, I might release it as 1.0.0, but it's not this day. :sweat_smile:
