### ISSUE TITLE
Integration with DataGrid

### ISSUE THREAD

**Issue by w0rldart** [TeamWertarbyte/material-ui-search-bar#94]
Is this extension compatible with DataGrid?  I've had a play with it, but I couldn't get it to work with DataGrid, meaning the search does not filter the data at all.

**Comment by leMaik** [comment]
Maybe it is, but you'd have to wire up the value from this component with the filtering logic from the data grid yourself.

It's out of scope for this project but if you get it to work and can provide a code sandbox with an example, that would be cool :+1:
